
on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:



      - name: Login via Az module
        run: az login --use-device-code


      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: Tej_RG
          dataFactoryName: prodadfbytej
          armTemplateFile: testadfbytej/ARMTemplateForFactory.json
          armTemplateParametersFile: testadfbytej/ARMTemplateParametersForFactory.json
          additionalParameters: 'factoryName=prodadfbytej'
